spring:
  application:
    name: basket-service

  mongodb:
      uri: mongodb://localhost:27017/basket-service
  data:
    redis:
      host: localhost
      port: 6379
      password: sa

  cache:
    redis:
      time-to-live: 60000


basket:
  client:
    platzi: https://api.escuelajs.co/api/v1/